### ISSUE TITLE
App requires Location Services Active for Launching (ref Wiki readme)

### ISSUE THREAD

**Issue by RipperDrone** [ImmersionRC/LapRFTimingAndroidPublic#3]
App requires location services of mobile phone to be active (why on earth??), otherwise doesn't launch correctly. After launch, location services can be switched off again, app then relies on BT only.

Desired status: No location services needed to launch app :-)

**Comment by tonycake** [comment]
Unfortunately I believe there is no way around this. From the android docs: 

"The other permission that you must declare is either ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION. A location permission is required because Bluetooth scans can be used to gather information about the location of the user. This information may come from the user's own devices, as well as Bluetooth beacons in use at locations such as shops and transit facilities."

**Comment by RipperDrone** [comment]
AFAIK, for other Android apps like SpeedyBee, there is no GPS ON required... hmmmm...?

**Comment by Nandox7** [comment]
For SpeedyBee they don't declare the permission on the app manifest but they request it on-demand when you try to use the BT service. 
If you select to give permission as always to the app the listed permissions get updated to reflect this also showing location.
Same requirement just a different approach to obtain it.

**Comment by Nandox7** [comment]
Btw with Android Q this gets "better" the permission needed will become ACCESS_FINE_LOCATION.

**Comment by tonycake** [comment]
I think we can close this issue, I don't see a way around it. 
It is not clear why other interfaces (such as cellular, and wifi) don't need the same permission, but it is what it is.

**Comment by RipperDrone** [comment]
Ok, just to be sure: To make LapRF work, I need to physically switch on GPS on my mobile, it's not about granting permission only. Location Services are turned on, the application makes the BT connection. After being BT connected, I can switch GPS off again and the BT connection stays.

I find it acceptable to share location / grant access to location (fine or coarse, do t matter), but it is very irritating and a big nuisance IMHO Having to toggle location services on and back off (turning off is for battery saving, it drains very quickly otherwise). For some reason other apps like SpeedyBee do NOT require a hard switching ON/OFF of location services...

**Comment by tonycake** [comment]
This is my understanding of how it works. If there is another way to do it I have no problem implementing it. Just to be clear, in earlier versions of Android this was not an issue, the issue was forced on the app in later versions. 
This is the code from the manifest that requests permission:
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />


And if you read the official docs on the same topic, it confirms that this is indeed correct: 
https://developer.android.com/guide/topics/connectivity/bluetooth

So..I am going to leave this one to the experts.

**Comment by RipperDrone** [comment]
@anthonycake - taking the risk you consider me stubborn: Even after reading the developer docs, it sounds to me that the app needs the permission to collect location information, since it will determine some more or less accurate location ID from the BT link itself. However, it does not tell that the location services on the mobile phone have to be switched on (which is GPS hardware, not related to BT hardware in any way). It really sounds like it'S about access permissions only, not about physically having to switch on GPS services over and above BT... so can we open this issue again and watch out for Andro experts, maybe?

**Comment by RipperDrone** [comment]
![image](https://user-images.githubusercontent.com/12601105/63968015-eb219180-ca9e-11e9-85b9-967ca307d53e.png)
